language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"

install:
    - "pip install requests"
    - "pip install pyparsing"
    - "pip install ."

script:
    - ./investor/test/test_investor.py

